comment:
  footer: |
    ---
    > I am a bot, and this is an automated message 🤖
labels:
  - name: ✖️ Invalid
    labeled:
      pr:
        body: Thank you @{{ pull_request.user.login }} for suggesting this. Please follow the pull request templates.
        action: close

  - name: ⛔ Don't Merge
    labeled:
      pr:
        body: This PR has been temporarily blocked from merging.
